version: "3.7"
networks:
  web:
    driver: bridge
  internal:
    driver: bridge

services:
  rl_database:
    image: mongo
    restart: always
    container_name: rl_database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGODB_DATABASE=rl
    networks:
      - internal
    volumes:
      - ${PWD}/.data/mongo/db:/data/db

  db:
    image: mongo-express
    container_name: rl_db
    environment:
      - ME_CONFIG_MONGODB_SERVER=${MDB_HOST}
      - ME_CONFIG_MONGODB_PORT=${MDB_PORT}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=${ADMIN_MDB}
      - ME_CONFIG_SITE_BASEURL=/db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    depends_on:
      - rl_database
    networks:
      - internal

  nginx:
    container_name: rl_nginx
    image: "nginx:stable"
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web
      - internal

  api:
    container_name: rl_api
    build:
      context: ./api
    tty: true
    restart: always
    volumes:
      - "./api:/app"
    networks:
      - internal
    links:
      - "rl_database"
    ports:
      - "8000:8000"

  app:
    build: ./app
    tty: true
    container_name: rl_app
    volumes:
      - "./app:/app"
    networks:
      - internal
    env_file:
      - .env
