import { validators } from "vue-form-generator";

export const schema = {
    fields: [
        {
            type: "input",
            label: "Title",
            model: "title",
            placeholder: "Book title",
            inputType: "text",
            styleClasses: "col s12",
            validator: validators.string,
        },
        {
            type: "select",
            label: "Type",
            model: "type",
            placeholder: "Book type",
            values: ["Fiction", "Non-fiction"],
            required: true,
            default: "Fiction",
            styleClasses: "col s12",
            validator: validators.required,
        },
        {
            type: "input",
            label: "Cover",
            model: "cover",
            placeholder: "Book Cover",
            hint: "Link to the book cover",
            required: true,
            inputType: "text",
            styleClasses: "col s12",
            validator: [validators.string, validators.required],
        },
        {
            type: "input",
            label: "Link to the book",
            model: "url",
            placeholder: "Link to the book",
            hint: "Link to the book",
            required: false,
            inputType: "text",
            styleClasses: "col s12",
            validator: validators.string,
        },
        {
            type: "input",
            label: "Language",
            model: "language",
            placeholder: "Book language",
            inputType: "text",
            styleClasses: "col s12",
            validator: validators.string,
        },
        {
            type: "input",
            label: "Rating",
            model: "rating",
            hint: "From 1 to 5",
            inputType: "number",
            placeholder: "Book rating (1 - 5)",
            required: true,
            min: 1,
            max: 5,
            styleClasses: "col s12",
            validator: [validators.number, validators.reuired],
        },
        {
            type: "input",
            label: "Pages",
            model: "pages",
            inputType: "number",
            hint: "Total pages",
            placeholder: "Count of page",
            required: true,
            min: 1,
            styleClasses: "col s12",
            validator: [validators.number, validators.reuired],
        },
        {
            type: "input",
            label: "Current page",
            model: "currentPage",
            inputType: "number",
            placeholder: "Current page number",
            required: false,
            min: 1,
            styleClasses: "col s12",
            validator: validators.number,
        },
        {
            type: "textArea",
            model: "note",
            inputType: "checkbox",
            label: "Note",
            hint: "Maximum 1200 symbols",
            max: 1200,
            rows: 10,
        },
        {
            type: 'vueMultiSelect',
            model: 'author',
            label: 'Author',
            placeholder: 'Add author',
            styleClasses: 'col s12',
            selectOptions: {
                multiple: false,
                key: 'name',
                id: '_id',
                trackBy: 'name',
                label: 'name',
                searchable: true,
                hideSelected: true,
            },
            values: []
        },
        {
            type: "checkbox",
            model: "notation",
            inputType: "checkbox",
            label: "Notation",
            default: false,
        },
        {
            type: "checkbox",
            model: "done",
            inputType: "checkbox",
            label: "Done",
            default: false,
        },
    ],
};

export const formOptions = {
    validateAfterLoad: true,
    validateAfterChanged: true,
    validateAsync: true,
};

export const defaultForm = {
    title: "",
    type: "",
    cover: "",
    url: "",
    language: "",
    rating: 1,
    pages: 1,
    currentPage: 1,
    note: "",
    author: [],
    status: "",
    notation: false,
    done: false,
};
