import { validators } from "vue-form-generator";

export const schema = {
  fields: [
    {
      type: "input",
      label: "Title",
      model: "title",
      placeholder: "Book title",
      required: true,
      inputType: "text",
      styleClasses: "col s12",
      validator: validators.required,
    },
    {
      type: "select",
      label: "Type",
      model: "type",
      placeholder: "Book type",
      values: ["Fiction", "Non-fiction"],
      required: true,
      default: "Fiction",
      styleClasses: "col s12",
      validator: validators.required,
    },
    {
      type: "input",
      label: "Cover",
      model: "cover",
      placeholder: "Book Cover",
      hint: "Link to the book cover",
      required: true,
      inputType: "text",
      styleClasses: "col s12",
      validator: [validators.string, validators.required],
    },
    {
      type: "input",
      label: "Link to the book",
      model: "url",
      placeholder: "Link to the book",
      hint: "Link to the book",
      required: false,
      inputType: "text",
      styleClasses: "col s12",
      validator: validators.string,
    },
    {
      type: "input",
      label: "Language",
      model: "language",
      placeholder: "Book language",
      inputType: "text",
      styleClasses: "col s12",
      validator: validators.string,
    },
    {
      type: "input",
      label: "Rating",
      model: "rating",
      hint: "From 1 to 5",
      inputType: "number",
      placeholder: "Book rating (1 - 5)",
      required: true,
      min: 1,
      max: 5,
      styleClasses: "col s12",
      validator: [validators.number, validators.required],
    },
    {
      type: "input",
      label: "Pages",
      model: "pages",
      inputType: "number",
      hint: "Total pages",
      placeholder: "Count of page",
      required: true,
      min: 1,
      styleClasses: "col s12",
      validator: [validators.number, validators.required],
    },
    {
      type: "input",
      label: "Current page",
      model: "currentPage",
      inputType: "number",
      placeholder: "Current page number",
      required: false,
      min: 1,
      styleClasses: "col s12",
      validator: validators.number,
    },
    {
      type: "textArea",
      model: "note",
      inputType: "text",
      label: "Note",
      hint: "Maximum 1200 symbols",
      max: 1200,
      rows: 10,
    },
    {
      type: "textArea",
      model: "bookIntro",
      inputType: "text",
      label: "Book Intro",
      rows: 110,
      hint: "Book intro, first chapter, text example...",
    },
    {
      type: "vueMultiSelect",
      model: "author",
      label: "Author",
      placeholder: "Add author",
      styleClasses: "col s12",
      required: true,
      selectOptions: {
        multiple: false,
        key: "name",
        id: "_id",
        trackBy: "name",
        label: "name",
        searchable: true,
        hideSelected: true,
      },
      values: [],
    },
    {
      type: "vueMultiSelect",
      model: "categories",
      label: "Categories",
      placeholder: "Add categories",
      styleClasses: "col s12",
      required: true,
      selectOptions: {
        multiple: true,
        key: "name",
        id: "_id",
        trackBy: "name",
        label: "name",
        searchable: true,
        hideSelected: true,
      },
      values: [],
    },
    {
      type: "select",
      label: "Status",
      model: "status",
      placeholder: "Status",
      values: [
        "Ready to start",
        "Reading",
        "Listerning",
        "Finished",
        "Leave",
        "Pending",
      ],
      required: true,
      default: "Fiction",
      styleClasses: "col s12",
      validator: validators.required,
    },
    {
      type: "checkbox",
      model: "notation",
      inputType: "checkbox",
      label: "Notation",
      default: false,
    },
    {
      type: "checkbox",
      model: "done",
      inputType: "checkbox",
      label: "Done",
      default: false,
    },
  ],
};

export const formOptions = {
  validateAfterLoad: true,
  validateAfterChanged: true,
  validateAsync: true,
};

export const defaultForm = {
  title: "",
  type: "",
  cover: "",
  url: "",
  language: "",
  rating: 1,
  pages: 1,
  currentPage: 1,
  note: "",
  bookIntro: "",
  author: [],
  categories: [],
  status: "",
  notation: false,
  done: false,
  owner: null,
};
